# Generated by Django 3.1 on 2021-08-12 09:52

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookOrder',
            fields=[
                ('srl', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=50, unique=True)),
                ('Ph', models.CharField(blank=True, max_length=50)),
                ('flat_bulding_name', models.CharField(blank=True, max_length=100)),
                ('street_name', models.CharField(blank=True, max_length=100)),
                ('postcode', models.CharField(blank=True, max_length=10)),
                ('service_details', models.CharField(blank=True, max_length=100)),
                ('infection', models.CharField(blank=True, max_length=100)),
                ('please_tell_us_about_your_place', models.CharField(blank=True, max_length=100)),
                ('is_the_property_furnished_or_empty', models.CharField(blank=True, max_length=100)),
                ('how_would_you_like_your_carpet_to_be_cleaned', models.CharField(blank=True, max_length=100)),
                ('most_of_our_customers_who_book_after_builders_cleaning_also_include', models.CharField(blank=True, max_length=100)),
                ('we_recommend_a_total_of_time_served', models.CharField(blank=True, max_length=100)),
                ('appointment_timing_date', models.CharField(blank=True, max_length=100)),
                ('total_price', models.CharField(blank=True, max_length=10)),
                ('user_description', tinymce.models.HTMLField()),
                ('note_final', models.CharField(blank=True, max_length=100)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Commercial_Cleaning_price', models.IntegerField(blank=True, null=True)),
                ('Domestic_Cleaning_price', models.IntegerField(blank=True, null=True)),
                ('Residential_Cleaning_price', models.IntegerField(blank=True, null=True)),
                ('infection_control_cleaning_services_yes', models.IntegerField(blank=True, null=True)),
                ('infection_control_cleaning_services_No', models.IntegerField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=1)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
