# Generated by Django 3.1 on 2021-08-12 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infectioncontrolcleaning', '0002_time_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time_id',
            name='time',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
