# Generated by Django 3.1 on 2021-08-12 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infectioncontrolcleaning', '0003_auto_20210812_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='time_id',
            name='Cost',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
