# Generated by Django 3.1 on 2021-08-12 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infectioncontrolcleaning', '0005_auto_20210812_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_ac',
            name='confirm',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
